const productsDb = [
  {
    productName: "عطر الهيل الملكي - عطر غزلان",
    id: 1,
    img: "../../assets/imgs/otour/1.webp",
    category: "otour",
    price: 175,
    rating: null,
    available: true,
    bestseller: true,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عطر الهيل جولد + عطر أفوكادو",
    id: 2,
    img: "../../assets/imgs/otour/2.webp",
    category: "otour",
    price: 193,
    rating: 5,
    available: true,
    bestseller: false,
    new: true,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عرض اليوم الوطني ( عطر الهيل + آوقيتين مروكي)",
    id: 3,
    img: "../../assets/imgs/otour/3.webp",
    category: "otour",
    price: 193,
    rating: null,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "أوقيتين كلمنتان فاخر +عطر غزلان",
    id: 4,
    img: "../../assets/imgs/otour/4.webp",
    category: "otour",
    price: 189,
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "أوقيتين بخور مروكي + عطر غزلان",
    id: 5,
    img: "../../assets/imgs/otour/5.webp",
    category: "otour",
    price: 169,
    rating: null,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عطر كولينان - عطر غزلان",
    id: 6,
    img: "../../assets/imgs/otour/6.webp",
    category: "otour",
    price: 177,
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عطر غزلان",
    id: 7,
    img: "../../assets/imgs/otour/7.webp",
    category: "otour",
    price: 139,
    rating: 3,
    available: true,
    bestseller: true,
    new: true,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عطر عود توباكو + أوقية بخور مروكي",
    id: 8,
    img: "../../assets/imgs/otour/8.webp",
    category: "otour",
    price: 132,
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عطر ذكرى + أوقية بخور مروكي ذكي",
    id: 9,
    img: "../../assets/imgs/otour/9.webp",
    category: "otour",
    price: 119,
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "أوقية مروكي فاخر + عطر عتيق مجاني",
    id: 10,
    img: "../../assets/imgs/otour/10.webp",
    category: "otour",
    price: 130,
    rating: null,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عطر SEVEN - عطر EIGHT",
    id: 11,
    img: "../../assets/imgs/otour/11.webp",
    category: "otour",
    price: 188,
    rating: null,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عطر كولينان",
    id: 12,
    img: "../../assets/imgs/otour/12.webp",
    category: "otour",
    price: 225,
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عطر عتيق الإصدار الجديد",
    id: 13,
    img: "../../assets/imgs/otour/13.webp",
    category: "otour",
    price: 130,
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: true,
  },
  {
    productName: "عطر ذكرى 30 مل",
    id: 14,
    img: "../../assets/imgs/otour/14.webp",
    category: "otour",
    price: 119,
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: true,
    offer: false,
  },
  {
    productName: "عطر الهيل الملكي",
    id: 15,
    img: "../../assets/imgs/otour/15.webp",
    category: "otour",
    price: 93,
    priceBeforeSale: "٢٥٤",
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "مجموعة Special Q",
    id: 16,
    img: "../../assets/imgs/otour/16.webp",
    category: "otour",
    price: 189,
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "مجموعة الميركة",
    id: 17,
    img: "../../assets/imgs/otour/17.webp",
    category: "otour",
    price: 99,
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عود توباكو - كولينان - ذكرى",
    id: 18,
    img: "../../assets/imgs/otour/18.webp",
    category: "otour",
    price: 299,
    rating: 5,
    available: false,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عرض العمودي الجديد",
    id: 19,
    img: "../../assets/imgs/oud/1.webp",
    category: "adhan",
    price: 179,
    rating: 5,
    available: true,
    bestseller: true,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "دهن الشيوخ 1 + 1 مجانًا",
    id: 20,
    img: "../../assets/imgs/oud/2.webp",
    category: "adhan",
    price: 188,
    rating: null,
    available: true,
    bestseller: false,
    new: true,
    backAgain: false,
    offer: false,
  },
  {
    productName: "دهن لاوسي معتق 25 سنة",
    id: 21,
    img: "../../assets/imgs/oud/3.webp",
    category: "adhan",
    price: 293,
    rating: null,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عرض الشيوخ - 4 أدهان (ربع)",
    id: 22,
    img: "../../assets/imgs/oud/4.webp",
    category: "adhan",
    price: 293,
    rating: null,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "2 دهن عود كمبودي بالورد",
    id: 23,
    img: "../../assets/imgs/oud/5.webp",
    category: "adhan",
    price: 99,
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عرض اليوم الوطني ( عطر الهيل + آوقيتين مروكي)",
    id: 24,
    img: "../../assets/imgs/oudBo5our/1.webp",
    category: "oudBo5our",
    price: 193,
    rating: null,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "أوقيتين كلمنتان فاخر +عطر غزلان",
    id: 25,
    img: "../../assets/imgs/oudBo5our/2.webp",
    category: "oudBo5our",
    price: 189,
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "أوقيتين بخور مروكي + عطر غزلان",
    id: 26,
    img: "../../assets/imgs/oudBo5our/3.webp",
    category: "oudBo5our",
    price: 169,
    rating: null,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عرض العمودي الجديد",
    id: 27,
    img: "../../assets/imgs/oudBo5our/4.webp",
    category: "oudBo5our",
    price: 179,
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عطر عود توباكو + أوقية بخور مروكي",
    id: 28,
    img: "../../assets/imgs/oudBo5our/5.webp",
    category: "oudBo5our",
    price: 132,
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عطر ذكرى + أوقية بخور مروكي ذكي",
    id: 29,
    img: "../../assets/imgs/oudBo5our/6.webp",
    category: "oudBo5our",
    price: 119,
    rating: null,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "ثلاث أوقيات كلمنتان فاخر جدًا",
    id: 30,
    img: "../../assets/imgs/oudBo5our/7.webp",
    category: "oudBo5our",
    price: 249,
    rating: 5,
    available: true,
    bestseller: false,
    new: true,
    backAgain: false,
    offer: false,
  },
  {
    productName: "أوقية مروكي فاخر + عطر عتيق مجاني",
    id: 31,
    img: "../../assets/imgs/oudBo5our/8.webp",
    category: "oudBo5our",
    price: 130,
    rating: null,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "البخور الذكي مروكي فاخر 140 غرام",
    id: 32,
    img: "../../assets/imgs/oudBo5our/9.webp",
    category: "oudBo5our",
    price: 185,
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "البخور الذكي مروكي فاخر 50 + 30 غرام هدية",
    id: 33,
    img: "../../assets/imgs/oudBo5our/10.webp",
    category: "oudBo5our",
    price: 119,
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "بخور العمودي الذكي",
    id: 34,
    img: "../../assets/imgs/oudBo5our/11.webp",
    category: "mabsos",
    price: 99,
    rating: 5,
    available: true,
    bestseller: false,
    new: true,
    backAgain: false,
    offer: false,
  },
  {
    productName: "بخور كلمنتان فاخر 3 أوقيات",
    id: 35,
    img: "../../assets/imgs/oudBo5our/12.webp",
    category: "oudBo5our",
    price: 129,
    priceBeforeSale: 392,
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "بخور هندي ملكي ثمن كيلو",
    id: 36,
    img: "../../assets/imgs/oudBo5our/13.webp",
    category: "oudBo5our",
    price: 2350,
    priceBeforeSale: 7723.4,
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "البخور الذكي مروكي طبيعي محسن ثمن كيلو",
    id: 37,
    img: "../../assets/imgs/oudBo5our/14.webp",
    category: "oudBo5our",
    price: 139,
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
];
export default productsDb;
