import styles from "./Home.module.css";
import Product from "../components/Product";

const bestsellers = [
  {
    productName: "عطر الهيل الملكي - عطر غزلان",
    id: 1256787,
    img: "../../assets/imgs/otour/1.webp",
    category: "otour",
    price: "١٧٥ ر.س",
    rating: null,
    available: true,
    bestseller: true,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عطر الهيل جولد + عطر أفوكادو",
    id: 2256787,
    img: "../../assets/imgs/otour/2.webp",
    category: "otour",
    price: "١٩٣ ر.س",
    rating: 5,
    available: true,
    bestseller: false,
    new: true,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عرض اليوم الوطني ( عطر الهيل + آوقيتين مروكي)",
    id: 3256787,
    img: "../../assets/imgs/otour/3.webp",
    category: "otour",
    price: "١٩٣ ر.س",
    rating: null,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "أوقيتين كلمنتان فاخر +عطر غزلان",
    id: 4256787,
    img: "../../assets/imgs/otour/4.webp",
    category: "otour",
    price: "١٨٩ ر.س",
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "أوقيتين بخور مروكي + عطر غزلان",
    id: 5256787,
    img: "../../assets/imgs/otour/5.webp",
    category: "otour",
    price: "١٦٩ ر.س",
    rating: null,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عطر كولينان - عطر غزلان",
    id: 6256787,
    img: "../../assets/imgs/otour/6.webp",
    category: "otour",
    price: "١٧٧ ر.س",
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عطر غزلان",
    id: 7256787,
    img: "../../assets/imgs/otour/7.webp",
    category: "otour",
    price: "١٣٩ ر.س",
    rating: 3,
    available: true,
    bestseller: true,
    new: true,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عطر عود توباكو + أوقية بخور مروكي",
    id: 8256787,
    img: "../../assets/imgs/otour/8.webp",
    category: "otour",
    price: "١٣٢ ر.س",
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عطر ذكرى + أوقية بخور مروكي ذكي",
    id: 2956787,
    img: "../../assets/imgs/otour/9.webp",
    category: "otour",
    price: "١١٩ ر.س",
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "أوقية مروكي فاخر + عطر عتيق مجاني",
    id: 1356787,
    img: "../../assets/imgs/otour/10.webp",
    category: "otour",
    price: "١٣٠ ر.س",
    rating: null,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عطر SEVEN - عطر EIGHT",
    id: 1456787,
    img: "../../assets/imgs/otour/11.webp",
    category: "otour",
    price: "١٨٨ ر.س",
    rating: null,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عطر كولينان",
    id: 1556787,
    img: "../../assets/imgs/otour/12.webp",
    category: "otour",
    price: "٢٢٥ ر.س",
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عطر عتيق الإصدار الجديد",
    id: 1656787,
    img: "../../assets/imgs/otour/13.webp",
    category: "otour",
    price: "١٣٠ ر.س",
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: true,
  },
  {
    productName: "عطر ذكرى 30 مل",
    id: 1756787,
    img: "../../assets/imgs/otour/14.webp",
    category: "otour",
    price: "١١٩ ر.س",
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: true,
    offer: false,
  },
  {
    productName: "عطر الهيل الملكي",
    id: 1856787,
    img: "../../assets/imgs/otour/15.webp",
    category: "otour",
    price: "٢٥٤ ر.س",
    priceAfterSale: "٩٣ ر.س",
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "مجموعة Special Q",
    id: 1956787,
    img: "../../assets/imgs/otour/16.webp",
    category: "otour",
    price: "١٨٩ ر.س",
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "مجموعة الميركة",
    id: 1266787,
    img: "../../assets/imgs/otour/17.webp",
    category: "otour",
    price: "٩٩ ر.س",
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عود توباكو - كولينان - ذكرى",
    id: 1276787,
    img: "../../assets/imgs/otour/18.webp",
    category: "otour",
    price: "٢٩٩ ر.س",
    rating: 5,
    available: false,
    bestseller: true,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عرض العمودي الجديد",
    id: 1276871,
    img: "../../assets/imgs/oud/1.webp",
    category: "oud",
    price: "١٧٩ ر.س",
    rating: 5,
    available: true,
    bestseller: true,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "دهن الشيوخ 1 + 1 مجانًا",
    id: 1276872,
    img: "../../assets/imgs/oud/2.webp",
    category: "oud",
    price: "١٨٨ ر.س",
    rating: null,
    available: true,
    bestseller: false,
    new: true,
    backAgain: false,
    offer: false,
  },
  {
    productName: "دهن لاوسي معتق 25 سنة",
    id: 1276873,
    img: "../../assets/imgs/oud/3.webp",
    category: "oud",
    price: "١٨٨ ر.س",
    rating: null,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عرض الشيوخ - 4 أدهان (ربع)",
    id: 1276874,
    img: "../../assets/imgs/oud/4.webp",
    category: "oud",
    price: "١٨٨ ر.س",
    rating: null,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "2 دهن عود كمبودي بالورد",
    id: 1276875,
    img: "../../assets/imgs/oud/5.webp",
    category: "oud",
    price: "١٨٨ ر.س",
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عرض اليوم الوطني ( عطر الهيل + آوقيتين مروكي)",
    id: 12768751,
    img: "../../assets/imgs/oudBo5our/1.webp",
    category: "oudBo5our",
    price: "١٩٣ ر.س",
    rating: null,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "أوقيتين كلمنتان فاخر +عطر غزلان",
    id: 12768752,
    img: "../../assets/imgs/oudBo5our/2.webp",
    category: "oudBo5our",
    price: "١٨٩ ر.س",
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "أوقيتين بخور مروكي + عطر غزلان",
    id: 12768753,
    img: "../../assets/imgs/oudBo5our/3.webp",
    category: "oudBo5our",
    price: "١٦٩ ر.س",
    rating: null,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عرض العمودي الجديد",
    id: 12768754,
    img: "../../assets/imgs/oudBo5our/4.webp",
    category: "oudBo5our",
    price: "١٧٩ ر.س",
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عطر عود توباكو + أوقية بخور مروكي",
    id: 12768755,
    img: "../../assets/imgs/oudBo5our/5.webp",
    category: "oudBo5our",
    price: "١٣٢ ر.س",
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "عطر ذكرى + أوقية بخور مروكي ذكي",
    id: 12768756,
    img: "../../assets/imgs/oudBo5our/6.webp",
    category: "oudBo5our",
    price: "١١٩ ر.س",
    rating: null,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "ثلاث أوقيات كلمنتان فاخر جدًا",
    id: 12768757,
    img: "../../assets/imgs/oudBo5our/7.webp",
    category: "oudBo5our",
    price: "٢٤٩ ر.س",
    rating: 5,
    available: true,
    bestseller: false,
    new: true,
    backAgain: false,
    offer: false,
  },
  {
    productName: "أوقية مروكي فاخر + عطر عتيق مجاني",
    id: 12768758,
    img: "../../assets/imgs/oudBo5our/8.webp",
    category: "oudBo5our",
    price: "١٣٠ ر.س",
    rating: null,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "البخور الذكي مروكي فاخر 140 غرام",
    id: 12768759,
    img: "../../assets/imgs/oudBo5our/9.webp",
    category: "oudBo5our",
    price: "١٨٥ ر.س",
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "البخور الذكي مروكي فاخر 50 + 30 غرام هدية",
    id: 127687510,
    img: "../../assets/imgs/oudBo5our/10.webp",
    category: "oudBo5our",
    price: "١١٩ ر.س",
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "بخور العمودي الذكي",
    id: 127687511,
    img: "../../assets/imgs/oudBo5our/11.webp",
    category: "oudBo5our",
    price: "٩٩ ر.س",
    rating: 5,
    available: true,
    bestseller: false,
    new: true,
    backAgain: false,
    offer: false,
  },
  {
    productName: "بخور كلمنتان فاخر 3 أوقيات",
    id: 127687512,
    img: "../../assets/imgs/oudBo5our/12.webp",
    category: "oudBo5our",
    price: "٣٩٢ ر.س",
    priceAfterSale: "١٢٩ ر.س",
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "بخور هندي ملكي ثمن كيلو",
    id: 127687513,
    img: "../../assets/imgs/oudBo5our/13.webp",
    category: "oudBo5our",
    price: "٧٬٧٢٣٫٤٠ ر.س",
    priceAfterSale: "٢٬٣٥٠ ر.س",
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
  {
    productName: "البخور الذكي مروكي طبيعي محسن ثمن كيلو",
    id: 127687514,
    img: "../../assets/imgs/oudBo5our/14.webp",
    category: "oudBo5our",
    price: "١٣٩ ر.س",
    rating: 5,
    available: true,
    bestseller: false,
    new: false,
    backAgain: false,
    offer: false,
  },
];

function Home() {
  return (
    <div>
      <div className={styles.heroImg}>
        <img src="../../assets/imgs/1.webp" alt="" />
      </div>
      <div className={styles.customerImg}>
        <a href="">
          <img src="../../assets/imgs/2.webp" alt="" />
        </a>
      </div>
      <h2 className={styles.headingSecond}>جديدنا والأكثر مبيعًا</h2>
      <div className="row  ">
        {bestsellers.map((item) => (
          <Product
            key={item.id}
            name={item.productName}
            img={item.img}
            priceA={item.priceA}
          />
        ))}
      </div>
      <div className={styles.perfumeImg}>
        <img src="../../assets/imgs/3.webp" alt="" />
      </div>
      <h2 className={styles.headingSecond}>صنع بحب..</h2>
      <div className="row  ">
        {bestsellers.map((item) => (
          <Product
            key={item.id}
            name={item.productName}
            img={item.img}
            priceA={item.priceA}
          />
        ))}
      </div>
    </div>
  );
}

export default Home;
